### ISSUE TITLE
[BUG] Custom Emoji List Keeps Clearing Itself

### ISSUE THREAD

**Issue by Piggby** [Moerill/Emojule#4] opened 2020-09-10 00:32 UTC
**Describe the Bug**
The custom emoji list will constantly clear itself after emojis are added, becoming completely empty.

**To Reproduce**
1. Create a fresh world.
2. Enable the Emojule module.
3. Go to Configure Settings and open the Custom Emoji Configurator.
4. Add any amount of custom emojis (the custom emojis will work while the Custom Emoji Configurator is open)
5. Press Close and Save Changes. The custom emoji list seems to clear itself after some time, sometimes on refresh, or when you open the Custom Emoji Configurator again. I can't figure out whether there is a consistent trigger here (so it could be a false correlation) but it eventually clears itself.

**Module Incompatibilities**
I'm using Forge VTT to host my server which has a Forge module built in, but I doubt it's the problem since I replicated the bug on the Standalone Virtual Tabletop Application, as shown below.

**Screenshot**
![image](https://user-images.githubusercontent.com/40404692/92667986-5e6cfe80-f2c2-11ea-8ade-569d67983ed2.png)

**Expected Behavior**
The custom emoji list should remain unchanged until you edit it again. Additionally, my players weren't able to use custom emojis that I added even when I could, but I'm not sure whether that's intended.

**Desktop**
 - OS: Windows 10 Home (Version 1909) (OS Build 18363.1016)
 - Browser: Google Chrome
 - FVTT Version: 0.6.6
 - Module Version: 0.3.0
 - 5e System Version: 0.96

**Comment by Moerill** [comment] 2020-09-10 08:44
should be fixed now, at least i can't reproduce it anymore.
Please check if you still encounter this error with v0.3.1 and either reopen this issue or create a new one.

**Closed as completed by Moerill** 2020-09-10 08:44 UTC
Labels: bug, good first issue

**Comment by Piggby** [comment] 2020-09-10 20:23
This exact issue seems to have been fixed, but it has a new trigger; whenever a new emoji is added, it clears the other emojis added beforehand after the Custom Emoji Configurator is closed, both on Forge VTT and the Standalone Tabletop Application.

Additionally, players seem to be still unable to use custom emojis.
![image](https://user-images.githubusercontent.com/40404692/92799368-9464be00-f368-11ea-90b0-b864debf5ad7.png)

**Comment by Moerill** [comment] 2020-09-10 21:24
oooh i completly failed to read the players not being able to use it stuff..
checking whats the issue there now

the other one is fixed now (though will be pushed with the other fix) .. stupid typos!

**Comment by Moerill** [comment] 2020-09-10 21:36
ok i hope now its fixed for real <_<
sorry and thanks for checking!

**Comment by Piggby** [comment] 2020-09-10 23:11
Everything seems to work properly now, thanks for your work!
